# Better ML model

This is a shorter, and better performing version of the previous machine learning model. Mainly, it puts the machine learning and data cleaning portions into functions, making the notebook more concise and readable.

Additionally, it is very aggressive about data cleaning. This feature is accidental - as explained later, but results in much better performance of the machine learning models.

In [1]:
# import required packages
import pandas as pd
import datetime
import numpy as np
import matplotlib.pyplot as plt

from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import scale

from sklearn.ensemble import RandomForestRegressor

## Function declarations

### Function to clean data
This function cleans data based on the dictionary 'limits'. Limits contains column names and associated (min,max) values. It returns a dataframe with the cleaned values.

As mentioned earlier, the aggressive data cleaning in this notebook is due to this function. The function should actually have prescribed '>=' and '<=' while imposing limits, but instead was '>' and '<' respectively. This resulted in removal of all min, max values from the columns of the dataframe. It resulted in much better performance of the machine learning models, though it dropped 1/3rd of the wells.

In [2]:
def clean_data(df, lims):
    for i in lims:
        df = df[df[i] > lims[i][0]]
        df = df[df[i] < lims[i][1]]

    return df

### Linear regression function

This function takes in a dataframe, and the non-categorical data columns and performs a linear regression on them. It returns the R^2, RMSE and the mean of the 5-fold CV R^2.

In [3]:
def lin_reg_func(df, data_cols):
    # get dummy values for the categorical variables
    df = pd.get_dummies(df)
    y = df.cum_oil_365.values

    # scaling the data columns
    X = scale(df[data_cols].values)
    X = np.concatenate((X, df.drop(data_cols, axis=1).values), axis=1)

    # create training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    reg = linear_model.LinearRegression()
    reg.fit(X_train, y_train)
    y_pred = reg.predict(X_test)
    r2_val = reg.score(X_test, y_test)
    rmse_val = np.sqrt(mean_squared_error(y_test, y_pred))
    cv_scores = cross_val_score(reg, X, y, cv=5)

    return r2_val, rmse_val, np.mean(cv_scores)

### Random forest regression function
This function takes in a dataframe, and the non-categorical data columns and performs a random forest regression on them. It returns the R^2, RMSE and the mean of the 5-fold CV R^2. Optionally, it also can take in the number of estimators for the random forest.

In [4]:
def random_forest_func(df, data_cols, num_estimators=500):
    df = pd.get_dummies(df)
    y = df.cum_oil_365.values
    X = scale(df[data_cols].drop(['cum_oil_365'],axis=1).values)
    X = np.concatenate((X, df.drop(data_cols, axis=1).values), axis=1)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    rf = RandomForestRegressor(n_estimators=num_estimators, random_state=42)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)
    r2_val = rf.score(X_test, y_test)
    rmse_val = np.sqrt(mean_squared_error(y_test, y_pred))
    cv_scores = cross_val_score(rf, X, y, cv=5)

    return r2_val, rmse_val, np.mean(cv_scores)

## Read in and combine data

In [5]:
# read csv data file
cum_prods = pd.read_csv('prod-by-operated-day.csv')
completions = pd.read_csv('completion.csv')
well_indices = pd.read_csv('well-index.csv')

In [6]:
# isolate the production variable desired
prods_365 = cum_prods.set_index('api')[['cum_oil_365']]

In [7]:
# eliminate rows in completions data where all column values are the same
completions.drop_duplicates(inplace=True)

# eliminate rows where both api and treatment date are the same
completions.drop_duplicates(subset=['api','treatment_date'],keep=False,inplace=True)

# dropping refracked wells
completions.drop_duplicates(subset=['api'],keep=False,inplace=True)

In [8]:
prods_365.reset_index(inplace=True)

In [9]:
final_data = pd.merge(prods_365, well_indices,how='inner',on='api')
final_data = pd.merge(final_data, completions,how='inner',on='api')

## Define and initialize dictionary for limits 
The limits dictionary is defined, and initialized to original (min,max) for each column.

In [10]:
limits = {'bottom':[],
       'fluid_bbl':[], 'fluid_bbl_per_ft':[], 'ft_per_stage':[], 'lateral_length':[],
       'max_treat_press':[], 'max_treat_rate':[], 'propp_lbs':[], 'propp_lbs_per_ft':[],
       'stages':[]}

for i in limits.keys():
    limits[i] = [min(final_data[i]), max(final_data[i])]

In [11]:
limits

{'bottom': [1450, 232035],
 'fluid_bbl': [0, 3766323],
 'fluid_bbl_per_ft': [0, 10711],
 'ft_per_stage': [0, 131211],
 'lateral_length': [2, 220106],
 'max_treat_press': [0, 101956],
 'max_treat_rate': [0.0, 9558.0],
 'propp_lbs': [0, 287883716],
 'propp_lbs_per_ft': [0, 695507],
 'stages': [1, 92]}

In [12]:
cols_to_drop = ['file_no', 'Current_Well_Name', 'Lease_Number', 'Township', 'Well_Type', 'Well_Status_Date',
                    'file_number', 'fluid_gal', 'fluid_gal_per_ft', 'top', 'Footages', 'Lease_Name', 'Field_Name', 'QQ',
                    'Range', 'CTB', 'Section', 'Well_Status', 'Original_Well_Name', 'Original_Operator',
                    'Current_Operator']
final_data.drop(labels=cols_to_drop, axis=1, inplace=True)
final_data.dropna(inplace=True)
today_date = datetime.date(2018, 5, 23)
spud_delta = (today_date - pd.to_datetime(final_data.Spud_Date)).dt.days
final_data['spud_timedelta'] = spud_delta
treatment_delta = (today_date - pd.to_datetime(final_data.treatment_date)).dt.days
final_data['treatment_timedelta'] = treatment_delta
final_data.drop(['Spud_Date', 'treatment_date'], axis=1, inplace=True)

In [13]:
data_cols = ['cum_oil_365', 'TD', 'Latitude', 'Longitude', 'bottom',
       'fluid_bbl', 'fluid_bbl_per_ft', 'ft_per_stage', 'lateral_length',
       'max_treat_press', 'max_treat_rate', 'propp_lbs', 'propp_lbs_per_ft',
       'stages', 'spud_timedelta', 'treatment_timedelta']

In [14]:
final_data = clean_data(final_data,limits)

In [15]:
final_data.describe()

,api,cum_oil_365,TD,Latitude,Longitude,bottom,fluid_bbl,fluid_bbl_per_ft,ft_per_stage,lateral_length,max_treat_press,max_treat_rate,propp_lbs,propp_lbs_per_ft,stages,spud_timedelta,treatment_timedelta
count,3.360000e+03,3360.000000,3360.000000,3360.000000,3360.000000,3360.000000,3.360000e+03,3360.000000,3360.000000,3360.000000,3360.000000,3360.000000,3.360000e+03,3360.000000,3360.000000,3360.000000,3360.000000
mean,3.305597e+13,92796.576190,19857.186905,47.998999,-103.022166,19716.257738,6.105406e+04,12.247917,316.324405,8992.665179,8234.144643,69.924702,3.122833e+06,700.902679,29.417560,2089.305357,1973.861012
std,2.923147e+10,50309.563565,2025.181784,0.476439,0.506199,2148.275442,4.891699e+04,87.682899,94.126675,1749.847593,2054.925981,494.125427,2.739074e+06,5267.129103,6.781302,219.593498,216.150097
min,3.300702e+13,5597.000000,1860.000000,46.833342,-104.044496,5527.000000,2.073000e+03,1.000000,1.000000,30.000000,8.000000,3.500000,2.557100e+04,2.000000,2.000000,1575.000000,1286.000000
25%,3.302502e+13,59949.250000,19480.000000,47.733559,-103.422115,19314.750000,3.781750e+04,4.000000,276.000000,8968.000000,7816.500000,31.100000,2.056340e+06,244.000000,26.000000,1913.000000,1787.000000
50%,3.305305e+13,84606.500000,20400.000000,47.993685,-102.975133,20302.000000,5.350750e+04,5.000000,312.000000,9421.000000,8400.000000,36.900000,2.837628e+06,309.000000,30.000000,2082.000000,1964.000000
75%,3.306102e+13,114022.750000,20891.000000,48.262812,-102.631811,20820.000000,7.191950e+04,7.000000,337.000000,9791.250000,8926.000000,41.400000,3.556481e+06,387.000000,32.000000,2253.000000,2151.000000
max,3.310503e+13,465897.000000,26908.000000,48.997699,-100.553543,26908.000000,1.514920e+06,1826.000000,2890.000000,19858.000000,77961.000000,9403.000000,3.970121e+07,102745.000000,71.000000,3360.000000,2896.000000

In [16]:
r2_rf, rmse_rf, cv_rf = random_forest_func(final_data, data_cols)
print('R2:',r2_rf)
print('RMSE:',rmse_rf)
print('Mean of 5-fold CV:',cv_rf)

R2: 0.692341767615
RMSE: 27438.7133352
Mean of 5-fold CV: 0.678088077542

## Changing max_bottom

In [17]:
limits['bottom'][1] = 50000

In [18]:
temp_data = clean_data(final_data,limits)
r2_rf, rmse_rf, cv_rf = random_forest_func(temp_data, data_cols)
print(r2_rf)
print(rmse_rf)
print(cv_rf)

0.692341767615
27438.7133352
0.678088077542

In [19]:
temp_data.describe()

,api,cum_oil_365,TD,Latitude,Longitude,bottom,fluid_bbl,fluid_bbl_per_ft,ft_per_stage,lateral_length,max_treat_press,max_treat_rate,propp_lbs,propp_lbs_per_ft,stages,spud_timedelta,treatment_timedelta
count,3.360000e+03,3360.000000,3360.000000,3360.000000,3360.000000,3360.000000,3.360000e+03,3360.000000,3360.000000,3360.000000,3360.000000,3360.000000,3.360000e+03,3360.000000,3360.000000,3360.000000,3360.000000
mean,3.305597e+13,92796.576190,19857.186905,47.998999,-103.022166,19716.257738,6.105406e+04,12.247917,316.324405,8992.665179,8234.144643,69.924702,3.122833e+06,700.902679,29.417560,2089.305357,1973.861012
std,2.923147e+10,50309.563565,2025.181784,0.476439,0.506199,2148.275442,4.891699e+04,87.682899,94.126675,1749.847593,2054.925981,494.125427,2.739074e+06,5267.129103,6.781302,219.593498,216.150097
min,3.300702e+13,5597.000000,1860.000000,46.833342,-104.044496,5527.000000,2.073000e+03,1.000000,1.000000,30.000000,8.000000,3.500000,2.557100e+04,2.000000,2.000000,1575.000000,1286.000000
25%,3.302502e+13,59949.250000,19480.000000,47.733559,-103.422115,19314.750000,3.781750e+04,4.000000,276.000000,8968.000000,7816.500000,31.100000,2.056340e+06,244.000000,26.000000,1913.000000,1787.000000
50%,3.305305e+13,84606.500000,20400.000000,47.993685,-102.975133,20302.000000,5.350750e+04,5.000000,312.000000,9421.000000,8400.000000,36.900000,2.837628e+06,309.000000,30.000000,2082.000000,1964.000000
75%,3.306102e+13,114022.750000,20891.000000,48.262812,-102.631811,20820.000000,7.191950e+04,7.000000,337.000000,9791.250000,8926.000000,41.400000,3.556481e+06,387.000000,32.000000,2253.000000,2151.000000
max,3.310503e+13,465897.000000,26908.000000,48.997699,-100.553543,26908.000000,1.514920e+06,1826.000000,2890.000000,19858.000000,77961.000000,9403.000000,3.970121e+07,102745.000000,71.000000,3360.000000,2896.000000

## Changing max fluid_bbl_per_ft

This changes the max fluid_bbl_per_ft very aggressively, from a max value of 1826, down to 100, which should be a more typical value in field.

In [20]:
limits['fluid_bbl_per_ft'][1] = 100

In [21]:
print('Original data shape:', final_data.shape)
temp_data = clean_data(final_data,limits)
r2_rf, rmse_rf, cv_rf = random_forest_func(temp_data, data_cols)
print('New data shape:',temp_data.shape)
print('R2:',r2_rf)
print('RMSE:',rmse_rf)
print('Mean of 5-fold CV:',cv_rf)

Original data shape: (3360, 20)
New data shape: (3342, 20)
R2: 0.752286137648
RMSE: 27204.350834
Mean of 5-fold CV: 0.677074906634

This shows this aggressive value for fluid_bbl_per_ft actually resulted in loss of only 18 wells out of 3360, and improved both R2 and RMSE dramatically.

In [41]:
temp_data.describe()

,api,cum_oil_365,TD,Latitude,Longitude,bottom,fluid_bbl,fluid_bbl_per_ft,ft_per_stage,lateral_length,max_treat_press,max_treat_rate,propp_lbs,propp_lbs_per_ft,stages,spud_timedelta,treatment_timedelta
count,3.342000e+03,3342.000000,3342.000000,3342.000000,3342.000000,3342.000000,3342.000000,3342.000000,3342.000000,3342.000000,3342.000000,3342.000000,3.342000e+03,3342.000000,3342.000000,3342.000000,3342.000000
mean,3.305593e+13,92931.687313,19861.378217,47.995820,-103.022103,19770.132555,60664.705566,6.267504,317.922801,9039.073908,8243.024237,70.128276,3.123534e+06,347.792041,29.416218,2089.717235,1974.367744
std,2.916298e+10,50378.559695,2028.493133,0.475565,0.507334,2020.960349,42100.156826,4.616021,91.654541,1632.980769,2055.619475,495.446874,2.746283e+06,303.491668,6.795601,219.922972,216.563671
min,3.300702e+13,5597.000000,1860.000000,46.833342,-104.044496,5527.000000,2073.000000,1.000000,65.000000,490.000000,8.000000,3.500000,2.557100e+04,2.000000,2.000000,1575.000000,1286.000000
25%,3.302502e+13,60088.750000,19500.500000,47.733333,-103.423273,19340.000000,37737.000000,4.000000,277.000000,8979.000000,7832.500000,31.100000,2.053054e+06,244.000000,26.000000,1912.250000,1786.250000
50%,3.305305e+13,84854.500000,20403.500000,47.992722,-102.973640,20310.000000,53565.500000,5.000000,312.000000,9424.000000,8408.000000,36.900000,2.834730e+06,308.000000,30.000000,2083.000000,1966.000000
75%,3.306102e+13,114143.500000,20894.750000,48.256679,-102.630536,20828.500000,72007.750000,7.000000,337.000000,9794.750000,8928.000000,41.500000,3.557374e+06,386.000000,32.000000,2253.750000,2153.000000
max,3.310503e+13,465897.000000,26908.000000,48.997699,-100.553543,26908.000000,506997.000000,60.000000,2890.000000,19858.000000,77961.000000,9403.000000,3.970121e+07,5195.000000,71.000000,3360.000000,2896.000000

## Adding in maturity
As defined in the previous notebook, the maturity is a parameter based on TD, by formation, and binned into 10 intervals.

In [22]:
# creating a new dataframe with_maturity to hold the final_data with maturity flag
with_maturity = final_data

In [23]:
with_maturity['Maturity'] = with_maturity['TD']
grouped_data = with_maturity.groupby('Produced_Pools')

In [24]:
for pool in with_maturity.Produced_Pools.unique():
    cur_td = grouped_data.get_group(pool).TD
    if len(cur_td) < 10: # if the formation has less than 10 data points, use one bin for all of them
        n_bins = 1
    else:
        n_bins = 10
    cur_range = max(cur_td) - min(cur_td) + 1 # 1 is added to take care of cases where only one data point exists
    cur_min = min(cur_td)
    bin_size = cur_range/n_bins
    vals = grouped_data.get_group(pool).TD.map(lambda x: (x -cur_min)// bin_size + 1).astype('str')
    #vals = [pool + vals.astype('str')]
    with_maturity.loc[vals.index,'Maturity'] = vals

In [25]:
with_maturity['Maturity'] = with_maturity['Maturity'] + '_' + with_maturity['Produced_Pools']
with_maturity['Maturity'] = with_maturity['Maturity'].astype('category')

In [26]:
temp_data = clean_data(with_maturity,limits)
r2_rf, rmse_rf, cv_rf = random_forest_func(temp_data, data_cols)
print('New data shape:',temp_data.shape)
print('R2:',r2_rf)
print('RMSE:',rmse_rf)
print('Mean of 5-fold CV:',cv_rf)

New data shape: (3342, 21)
R2: 0.753094547782
RMSE: 27159.9240812
Mean of 5-fold CV: 0.677813410391

So the maturity results in a marginal improvement to the model performance.

## Add in frac intensity

As defined in the previous notebook, the frac intensity is just a parameter based on the max treat pressure, by formation, and binned into 10 intervals.

In [27]:
# creating a new dataframe with_maturity to hold the final_data with maturity flag
with_frac_intensity = with_maturity

In [28]:
with_frac_intensity['Frac_intensity'] = with_frac_intensity['max_treat_press']

In [29]:
grouped_data = with_frac_intensity.groupby('Produced_Pools')
for pool in with_frac_intensity.Produced_Pools.unique():
    cur_press = grouped_data.get_group(pool).max_treat_press
    if len(cur_press) < 10: # if the formation has less than 10 data points, use one bin for all of them
        n_bins = 1
    else:
        n_bins = 10
    cur_range = max(cur_press) - min(cur_press) + 1 # 1 is added to take care of cases where only one data point exists
    cur_min = min(cur_press)
    bin_size = cur_range/n_bins
    vals = grouped_data.get_group(pool).max_treat_press.map(lambda x: (x -cur_min)// bin_size + 1).astype('str')
    #vals = [pool + vals.astype('str')]
    with_frac_intensity.loc[vals.index,'Frac_intensity'] = vals

In [30]:
with_frac_intensity['Frac_intensity'] = with_frac_intensity['Frac_intensity'] + '_' + with_frac_intensity['Produced_Pools']

In [31]:
with_frac_intensity['Frac_intensity'] = with_frac_intensity['Frac_intensity'].astype('category')

In [32]:
temp_data = clean_data(with_frac_intensity,limits)
r2_rf, rmse_rf, cv_rf = random_forest_func(temp_data, data_cols)
print('New data shape:',temp_data.shape)
print('R2:',r2_rf)
print('RMSE:',rmse_rf)
print('Mean of 5-fold CV:',cv_rf)

New data shape: (3342, 22)
R2: 0.75313748707
RMSE: 27157.5622894
Mean of 5-fold CV: 0.676897924077

# Conclusion

Cleaning the data very aggresively results in a much better model than before. The best R^2 and RMSE values obtained were 0.7531 and 27157.56 barrels, respectively, with fracture intensity and maturity providing marginal improvements to the model. The previous machine learning model achieved a best-case R^2 and RMSE of 0.66 and 30140 bbls, respectively.

This works in this situation because we are still left with plenty of wells (3342).